[project]
name="video_game_database"
version="1.0.0"
requires-python=">=3.11.0"
dependencies =[
    "dotenv",
    "jupyter",
    "numpy",
    "pandas",
    "psycopg2-binary",
    "seaborn",
]

[pyproject.optional-dependencies]
dev = [
    "pytest"
]

[build-system]
requires = [
    "setuptools>=68",
    "wheel"
]

build-backend="setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]